### ISSUE TITLE
Onestep install with pip

### ISSUE THREAD

**Issue by leipert** [nareike/adhs#1]

**Comment by miku** [comment]
@leipert do you want to create a PR? Otherwise I would try to prepare a PR for this by tonight.

**Comment by leipert** [comment]
@miku I talked with @nareike about it. He want's to implement it. But I think if you create a PR, it would make him happy as well :+1: 

EDIT: I would create one too, but I think he would rather see me fixing his issues in leipert/vsb :dancer:

**Comment by miku** [comment]
@leipert, very nice. I added some packaging support in #8. I would even offer to maintain a pypi package, if @nareike is interested.

Btw, just did a tour of http://leipert.github.io/vsb/ – and wow, you have a great intuition for user interfaces.
